In [1]:
#1.Import NumPy
import numpy as np


In [2]:
#2.Create Sales Dataset
sales = np.array([
    12000, 15000, 18000, 11000, 22000,
    25000, 17000, 30000, 28000, 19000
])

print(sales)

[12000 15000 18000 11000 22000 25000 17000 30000 28000 19000]


In [3]:
#3.Basic Information
print("Number of records:", sales.size)
print("Shape:", sales.shape)
print("Data type:", sales.dtype)

Number of records: 10
Shape: (10,)
Data type: int32


In [4]:
#4. Total, Average, Highest, Lowest Sales
print("Total Sales:", np.sum(sales))
print("Average Sales:", np.mean(sales))
print("Highest Sales:", np.max(sales))
print("Lowest Sales:", np.min(sales))

Total Sales: 197000
Average Sales: 19700.0
Highest Sales: 30000
Lowest Sales: 11000


In [5]:
#5. Median and Standard Deviation
print("Median Sales:", np.median(sales))
print("Standard Deviation:", np.std(sales))
print("Variance:", np.var(sales))

Median Sales: 18500.0
Standard Deviation: 6132.699242584786
Variance: 37610000.0


In [6]:
#6. Find Highest and Lowest Sale Position
highest_index = np.argmax(sales)
lowest_index = np.argmin(sales)

print("Highest Sale:", sales[highest_index])
print("Highest Sale Index:", highest_index)

print("Lowest Sale:", sales[lowest_index])
print("Lowest Sale Index:", lowest_index)

Highest Sale: 30000
Highest Sale Index: 7
Lowest Sale: 11000
Lowest Sale Index: 3


In [9]:
#7. Filtering Data
high_sales = sales[sales > 20000]

print(high_sales)

[22000 25000 30000 28000]


In [10]:
medium_sales = sales[(sales >= 15000) & (sales <= 25000)]

print(medium_sales)

[15000 18000 22000 25000 17000 19000]


In [11]:
#8. Count Sales Above ₹20,000
count = np.sum(sales > 20000)

print("Sales above 20000:", count)

Sales above 20000: 4


In [12]:
#9. Percentage Calculation
discount = sales * 0.10

final_sales = sales - discount

print(final_sales)

[10800. 13500. 16200.  9900. 19800. 22500. 15300. 27000. 25200. 17100.]


In [13]:
#10. Sales Growth
previous_sales = np.array([
    10000, 14000, 16000, 12000, 20000,
    23000, 15000, 27000, 25000, 17000
])

growth = ((sales - previous_sales) / previous_sales) * 100

print("Growth Percentage:")
print(growth)

Growth Percentage:
[20.          7.14285714 12.5        -8.33333333 10.          8.69565217
 13.33333333 11.11111111 12.         11.76470588]


In [14]:
#11. Monthly Sales
monthly_sales = np.array([
    12000, 15000, 18000, 11000,
    22000, 25000, 17000, 30000,
    28000, 19000, 32000, 35000
])

months = np.array([
    "Jan", "Feb", "Mar", "Apr",
    "May", "Jun", "Jul", "Aug",
    "Sep", "Oct", "Nov", "Dec"
])

for month, sale in zip(months, monthly_sales):
    print(month, sale)

Jan 12000
Feb 15000
Mar 18000
Apr 11000
May 22000
Jun 25000
Jul 17000
Aug 30000
Sep 28000
Oct 19000
Nov 32000
Dec 35000


In [15]:
#12. Best Month
best_month_index = np.argmax(monthly_sales)

print("Best Month:", months[best_month_index])
print("Highest Sales:", monthly_sales[best_month_index])

Best Month: Dec
Highest Sales: 35000


In [16]:
#13. Worst Month
worst_month_index = np.argmin(monthly_sales)

print("Worst Month:", months[worst_month_index])
print("Lowest Sales:", monthly_sales[worst_month_index])

Worst Month: Apr
Lowest Sales: 11000


In [17]:
#14. Sort Sales
sorted_sales = np.sort(sales)

print(sorted_sales)

[11000 12000 15000 17000 18000 19000 22000 25000 28000 30000]


In [18]:
#Descending order:
descending_sales = np.sort(sales)[::-1]

print(descending_sales)

[30000 28000 25000 22000 19000 18000 17000 15000 12000 11000]


In [19]:
#15. Unique Values
data = np.array([100, 200, 100, 300, 200, 400, 500, 300])

unique_values = np.unique(data)

print(unique_values)

[100 200 300 400 500]


In [20]:
#16. Handle Missing Values
sales_with_nan = np.array([
    12000, 15000, np.nan,
    18000, 22000, np.nan,
    25000
])

print("Mean:", np.nanmean(sales_with_nan))
print("Maximum:", np.nanmax(sales_with_nan))
print("Minimum:", np.nanmin(sales_with_nan))

Mean: 18400.0
Maximum: 25000.0
Minimum: 12000.0


In [21]:
#17. Replace Missing Values
mean_sales = np.nanmean(sales_with_nan)

clean_sales = np.where(
    np.isnan(sales_with_nan),
    mean_sales,
    sales_with_nan
)

print(clean_sales)

[12000. 15000. 18400. 18000. 22000. 18400. 25000.]


In [22]:
#18. 2D Array — Product Sales
sales_data = np.array([
    [12000, 15000, 18000],
    [20000, 22000, 25000],
    [10000, 14000, 16000],
    [30000, 28000, 32000]
])

print(sales_data)

[[12000 15000 18000]
 [20000 22000 25000]
 [10000 14000 16000]
 [30000 28000 32000]]


In [23]:
#Rows ka total:
row_total = np.sum(sales_data, axis=1)

print(row_total)

[45000 67000 40000 90000]


In [24]:
#Columns ka total:
column_total = np.sum(sales_data, axis=0)

print(column_total)

[72000 79000 91000]


In [ ]:
#19. Product-wise Average
product_average = np.mean(sales_data, axis=1)

print(product_average)


In [25]:
#20. Column-wise Average
monthly_average = np.mean(sales_data, axis=0)

print(monthly_average)

[18000. 19750. 22750.]


In [26]:
#21. Array banana
import numpy as np

arr = np.array([10, 20, 30, 40, 50])

print(arr)

[10 20 30 40 50]


In [27]:
#2D data:
data = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])

print(data)

[[10 20 30]
 [40 50 60]
 [70 80 90]]


In [28]:
#22. Array Information
print(data.shape)
print(data.ndim)
print(data.size)
print(data.dtype)

(3, 3)
2
9
int32


In [29]:
#23. arange()
numbers = np.arange(1, 101)

print(numbers)

[  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
  91  92  93  94  95  96  97  98  99 100]


In [30]:
#24. linspace()
values = np.linspace(0, 100, 10)

print(values)

[  0.          11.11111111  22.22222222  33.33333333  44.44444444
  55.55555556  66.66666667  77.77777778  88.88888889 100.        ]


In [31]:
#25. Random Data
sales = np.random.randint(1000, 50000, 100)

print(sales)

[23852 29095 21252 44021 28020 37190  2011 49367 45910 44916  5533 45353
 15033 11779 31915 43283 39497 35600  1297 10664 14095 27045 49388 33286
  8568 31126 18107 32468 29567  6527 12323 31843 49662 27263 43289  6688
  4003 25425 14833 16786 27789 22063 25198 36668 23384 18693 45398  4154
 34342 36541 35007  9262 11759 11468 11200 45292 10518 16247  4686 29487
 21272 38877  4166 22481 21262  4080 25594 12407  1780  7385 24287 20591
 22126 21440 36764 13834 38570 13404 28686 36027 10965  1253 27168 42643
 44151 14202 21229  3618 24143 29564  4580 49846 32003 26307 11723  4393
 11187 15093 27951 25830]


In [32]:
#100 random sales values.
ratings = np.random.randint(1, 6, 100)

print(ratings)

[5 5 3 4 4 5 3 2 3 3 4 3 2 5 2 3 3 1 2 5 4 4 1 3 2 3 4 2 5 5 3 3 3 3 4 4 3
 2 5 4 3 5 1 5 4 3 3 3 3 5 4 1 2 2 2 1 3 4 2 3 1 2 1 2 1 4 4 3 3 3 1 1 4 1
 2 4 5 2 3 3 3 2 1 4 1 1 2 4 1 4 1 5 3 5 4 2 4 5 4 3]


In [33]:
#26. seed()
np.random.seed(42)

sales = np.random.randint(1000, 50000, 100)

print(sales)

[16795  1860 39158 45732 12284  7265 17850 38194 22962 48191 45131 17023
 42090  2685  1769  3433  6311 38819 40188 18568 20769 29693  7396 28480
 42434 26658 19942 19431  3747  1189 20118 36773  2899  2267 32551 12394
  4556  4890 42606 31740 15502 22777 11627  9792 44323 44021  9433 44001
 12016 24897  3612 24483 49555 18159 45974 41994 15541 36920 27531  2585
  4943 24939 20457  2021 12653 44573 14417 41757 10692 46758  7873  6675
  1161 38065 27557 34763 33606 12534 30127 41397 26851  2016 25253 25276
 24247 25300  9529 18262 10268 22271 13185 22243 40099  9571 40976 39044
 49984 41774  3568  3027]


In [37]:
#27.. argmax() and argmin()
index = np.argmax(sales)

print(index)
print(sales[index])

5
30000


In [38]:
#Lowest value:
index = np.argmin(sales)

print(index)
print(sales[index])

0
10000


In [39]:
#28. Percentile
print(np.percentile(sales, 25))
print(np.percentile(sales, 50))
print(np.percentile(sales, 75))

12750.0
17500.0
23750.0


In [40]:
#29. Filtering
high_sales = sales[sales > 20000]

print(high_sales)

[25000 30000]


In [41]:
#30. where()
result = np.where(
    sales >= 20000,
    "High",
    "Low"
)

print(result)

['Low' 'Low' 'High' 'Low' 'High' 'High']


In [44]:
#31. Reshape
data = np.arange(1, 13)

new_data = data.reshape(3, 4)

print(new_data)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [47]:
#32. Sorting
sales = np.array([5000, 2000, 9000, 3000, 7000])

sorted_sales = np.sort(sales)

print(sorted_sales)

[2000 3000 5000 7000 9000]


In [48]:
#Descending:
descending = np.sort(sales)[::-1]

print(descending)

[9000 7000 5000 3000 2000]


In [49]:
#33. Unique Values
cities = np.array([
    "Delhi",
    "Patna",
    "Delhi",
    "Mumbai",
    "Patna"
])

print(np.unique(cities))

['Delhi' 'Mumbai' 'Patna']


In [50]:
#Unique values ke saath count:
cities, counts = np.unique(
    cities,
    return_counts=True
)

print(cities)
print(counts)

['Delhi' 'Mumbai' 'Patna']
[2 1 2]


In [51]:
#34. Cumulative Sum
sales = np.array([
    10000, 15000, 20000, 25000
])

running_total = np.cumsum(sales)

print(running_total)

[10000 25000 45000 70000]


In [52]:
#35. Cumulative Maximum
sales = np.array([
    10000, 15000, 12000, 20000, 18000
])

running_max = np.maximum.accumulate(sales)

print(running_max)

[10000 15000 15000 20000 20000]


In [54]:
#36.Growth Rate
old_sales = np.array([
    10000, 20000, 30000
])

new_sales = np.array([
    12000, 22000, 36000
])

growth = (
    (new_sales - old_sales)
    / old_sales
) * 100

print(growth)

[20. 10. 20.]


In [55]:
#37. Concatenate
a = np.array([10, 20, 30])
b = np.array([40, 50, 60])

result = np.concatenate([a, b])

print(result)

[10 20 30 40 50 60]


In [56]:
#38. vstack() and hstack()
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(np.vstack([a, b]))

[[1 2 3]
 [4 5 6]]


In [57]:
#39. Outlier Detection
sales = np.array([
    10000, 12000, 15000,
    14000, 16000, 18000,
    20000, 100000
])

Q1 = np.percentile(sales, 25)
Q3 = np.percentile(sales, 75)

IQR = Q3 - Q1

lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR

outliers = sales[
    (sales < lower) |
    (sales > upper)
]

print("Outliers:", outliers)

Outliers: [100000]
